#ifndef SOLAR_CONSTANTS_H
#define SOLAR_CONSTANTS_H

#include <math.h>

#define SOLAR_G 6.67430e-11
#define SOLAR_AU_METERS 149597870700.0
#define SOLAR_DAY_SECONDS 86400.0

#define SOLAR_SUN_MASS_KG 1.98847e30
#define SOLAR_SUN_RADIUS_M 695700000.0

#define SOLAR_MERCURY_MASS_KG 3.3011e23
#define SOLAR_MERCURY_RADIUS_M 2439700.0
#define SOLAR_MERCURY_SEMI_MAJOR_AXIS_M 57909050000.0
#define SOLAR_MERCURY_ECCENTRICITY 0.205630
#define SOLAR_MERCURY_PERIHELION_M \
    (SOLAR_MERCURY_SEMI_MAJOR_AXIS_M * (1.0 - SOLAR_MERCURY_ECCENTRICITY))
#define SOLAR_MERCURY_PERIHELION_SPEED_MPS \
    (sqrt(SOLAR_G * SOLAR_SUN_MASS_KG * \
        ((2.0 / SOLAR_MERCURY_PERIHELION_M) - (1.0 / SOLAR_MERCURY_SEMI_MAJOR_AXIS_M))))

#define SOLAR_VENUS_MASS_KG 4.8675e24
#define SOLAR_VENUS_RADIUS_M 6051800.0
#define SOLAR_VENUS_SEMI_MAJOR_AXIS_M 108208000000.0
#define SOLAR_VENUS_ECCENTRICITY 0.006772
#define SOLAR_VENUS_PERIHELION_M \
    (SOLAR_VENUS_SEMI_MAJOR_AXIS_M * (1.0 - SOLAR_VENUS_ECCENTRICITY))
#define SOLAR_VENUS_PERIHELION_SPEED_MPS \
    (sqrt(SOLAR_G * SOLAR_SUN_MASS_KG * \
        ((2.0 / SOLAR_VENUS_PERIHELION_M) - (1.0 / SOLAR_VENUS_SEMI_MAJOR_AXIS_M))))

#define SOLAR_EARTH_MASS_KG 5.9736e24
#define SOLAR_EARTH_RADIUS_M 6371000.0
#define SOLAR_EARTH_SEMI_MAJOR_AXIS_M 149597887155.76578
#define SOLAR_EARTH_ECCENTRICITY 0.01671022
#define SOLAR_EARTH_PERIHELION_M \
    (SOLAR_EARTH_SEMI_MAJOR_AXIS_M * (1.0 - SOLAR_EARTH_ECCENTRICITY))
#define SOLAR_EARTH_PERIHELION_SPEED_MPS \
    (sqrt(SOLAR_G * SOLAR_SUN_MASS_KG * \
        ((2.0 / SOLAR_EARTH_PERIHELION_M) - (1.0 / SOLAR_EARTH_SEMI_MAJOR_AXIS_M))))

#define SOLAR_MOON_MASS_KG 7.346e22
#define SOLAR_MOON_RADIUS_M 1737400.0
#define SOLAR_MOON_SEMI_MAJOR_AXIS_M 384400000.0
#define SOLAR_MOON_ECCENTRICITY 0.0549
#define SOLAR_MOON_PERIGEE_M \
    (SOLAR_MOON_SEMI_MAJOR_AXIS_M * (1.0 - SOLAR_MOON_ECCENTRICITY))
#define SOLAR_MOON_PERIGEE_SPEED_MPS \
    (sqrt(SOLAR_G * (SOLAR_EARTH_MASS_KG + SOLAR_MOON_MASS_KG) * \
        ((2.0 / SOLAR_MOON_PERIGEE_M) - (1.0 / SOLAR_MOON_SEMI_MAJOR_AXIS_M))))

#define SOLAR_MARS_MASS_KG 6.419e23
#define SOLAR_MARS_RADIUS_M 3390000.0
#define SOLAR_MARS_SEMI_MAJOR_AXIS_M 227900000000.0
#define SOLAR_MARS_ECCENTRICITY 0.0934
#define SOLAR_MARS_PERIHELION_M \
    (SOLAR_MARS_SEMI_MAJOR_AXIS_M * (1.0 - SOLAR_MARS_ECCENTRICITY))
#define SOLAR_MARS_APHELION_M \
    (SOLAR_MARS_SEMI_MAJOR_AXIS_M * (1.0 + SOLAR_MARS_ECCENTRICITY))
#define SOLAR_MARS_PERIHELION_SPEED_MPS \
    (sqrt(SOLAR_G * SOLAR_SUN_MASS_KG * \
        ((2.0 / SOLAR_MARS_PERIHELION_M) - (1.0 / SOLAR_MARS_SEMI_MAJOR_AXIS_M))))

#define SOLAR_RENDER_UNITS_PER_AU 10.0
#define SOLAR_MIN_VISIBLE_BODY_RADIUS 0.5f
#define SOLAR_ILLUSTRATIVE_PLANET_RADIUS 0.12f
#define SOLAR_ILLUSTRATIVE_MOON_DISTANCE_FACTOR 8.0

#endif
