#ifndef SOLAR_SATELLITE_CATALOG_H
#define SOLAR_SATELLITE_CATALOG_H

#include <stddef.h>

#include "satellite.h"

/* Moon catalogs generated by tools/satellite_catalog.py from pinned JPL
 * snapshots in data/ (SPEC R8, R18, R19). Each array keeps JPL's table order;
 * `major` marks the rounded moons that also belong to the main scene. */
#define SOLAR_JOVIAN_MOON_COUNT 115
#define SOLAR_SATURNIAN_MOON_COUNT 291
#define SOLAR_URANIAN_MOON_COUNT 29
#define SOLAR_NEPTUNIAN_MOON_COUNT 16
#define SOLAR_PLUTONIAN_MOON_COUNT 5
#define SOLAR_DIDYMOS_MOON_COUNT 1
extern const SatelliteDefinition solar_jovian_moons[SOLAR_JOVIAN_MOON_COUNT];
extern const SatelliteDefinition solar_saturnian_moons[SOLAR_SATURNIAN_MOON_COUNT];
extern const SatelliteDefinition solar_uranian_moons[SOLAR_URANIAN_MOON_COUNT];
extern const SatelliteDefinition solar_neptunian_moons[SOLAR_NEPTUNIAN_MOON_COUNT];
extern const SatelliteDefinition solar_plutonian_moons[SOLAR_PLUTONIAN_MOON_COUNT];
extern const SatelliteDefinition solar_didymos_moons[SOLAR_DIDYMOS_MOON_COUNT];

typedef struct SatelliteCatalog {
    BodyId planet;
    const SatelliteDefinition *moons;
    size_t count;
} SatelliteCatalog;

/* Catalog of a giant planet's, Pluto's or Didymos's moons, or NULL. */
const SatelliteCatalog *satellite_catalog_for(BodyId planet);

#endif
