"""Write a file's bytes as a C array so a build can embed a small asset.

Usage: python3 tools/embed_binary.py INPUT OUTPUT SYMBOL
The output defines `static const unsigned char SYMBOL[]` and
`static const int SYMBOL_size`; include it from exactly one .c file.
"""
import sys
from pathlib import Path


def main() -> int:
    if len(sys.argv) != 4 or not sys.argv[3].isidentifier():
        print(__doc__.strip(), file=sys.stderr)
        return 2
    data = Path(sys.argv[1]).read_bytes()
    rows = [", ".join(f"0x{b:02x}" for b in data[i:i + 16]) for i in range(0, len(data), 16)]
    body = ",\n    ".join(rows)
    Path(sys.argv[2]).write_text(
        f"/* Generated by tools/embed_binary.py from {Path(sys.argv[1]).as_posix()}; do not edit. */\n"
        f"static const unsigned char {sys.argv[3]}[] = {{\n    {body}\n}};\n"
        f"static const int {sys.argv[3]}_size = {len(data)};\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
