#!/usr/bin/env python3
"""Explicit serialized Horizons snapshot; offline generation/check on normal builds."""
import argparse
from datetime import datetime, timezone
import json
from pathlib import Path
from urllib.parse import urlencode
from urllib.request import urlopen

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / 'data/planet_epoch.json'
GENERATED = ROOT / 'src/sim/planet_epoch.inc'
EPOCH = 2461200.5
PLANETS = [('Mercury',199),('Venus',299),('Earth',399),('Mars',499),
           ('Jupiter',599),('Saturn',699),('Uranus',799),('Neptune',899)]


def refresh():
    planets = []
    for name, id in PLANETS:
        params = {'format':'json','COMMAND':str(id),'CENTER':'500@10','EPHEM_TYPE':'VECTORS',
                  'TLIST':str(EPOCH),'OUT_UNITS':'KM-S','REF_PLANE':'ECLIPTIC',
                  'VEC_TABLE':'2','VEC_CORR':'NONE','CSV_FORMAT':'YES','OBJ_DATA':'NO'}
        url = 'https://ssd.jpl.nasa.gov/api/horizons.api?' + urlencode(params)
        with urlopen(url, timeout=120) as response:
            payload = json.load(response)
        result = payload['result']
        rows = result.split('$$SOE')[1].split('$$EOE')[0].strip().splitlines()
        if len(rows) != 1 or 'Ecliptic of J2000.0' not in result:
            raise ValueError('Horizons epoch/frame contract changed')
        row = [v.strip() for v in rows[0].split(',')]
        if float(row[0]) != EPOCH:
            raise ValueError('epoch mismatch')
        planets.append({'name':name, 'horizons_id':id, 'source':url,
                        'position_km':[float(v) for v in row[2:5]],
                        'velocity_km_s':[float(v) for v in row[5:8]]})
        print(f'Fetched {name} at JD {EPOCH}', flush=True)
    DATA.write_text(json.dumps({'epoch':EPOCH,'frame':'J2000 ecliptic','center':'Sun',
        'checked':datetime.now(timezone.utc).isoformat(),'planets':planets},indent=2)+'\n')


def output():
    snapshot = json.loads(DATA.read_text())
    if snapshot['epoch'] != EPOCH or [p['name'] for p in snapshot['planets']] != [p[0] for p in PLANETS]:
        raise ValueError('review changed planetary snapshot')
    lines = ['/* Generated by tools/planet_epoch.py; Sun-centered J2000 ecliptic, SI, Y north. */']
    for p in snapshot['planets']:
        pos, vel = p['position_km'], p['velocity_km_s']
        values = [v*1000 for v in (pos[0],pos[2],pos[1],vel[0],vel[2],vel[1])]
        lines.append('{' + ','.join(format(v,'.17g') for v in values) + '},')
    return '\n'.join(lines)+'\n'


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--refresh',action='store_true')
    parser.add_argument('--check',action='store_true')
    args=parser.parse_args()
    if args.refresh: refresh()
    text=output()
    if args.check:
        if GENERATED.read_text()!=text: raise ValueError('planetary include is stale')
        print('Planetary epoch snapshot verified')
    else: GENERATED.write_text(text)
